{% set name = "brightway2" %}
{% set version = "2.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e9521fbb6368689e784d7f5454e89739db3a7d7ea6c64a6089d9e5f45f49a4a7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - appdirs
    - asteval
    - bw2analyzer <0.10.99
    - bw2calc =1.8.2
    - bw2data =3.6.6
    - bw2io <0.8.9
    - bw2parameters >=0.6.5
    - docopt
    - eight
    - flask
    - future
    - lxml
    - numpy
    - peewee >=3.0
    - psutil
    - pyprind
    - python >=3.6
    - requests
    - scipy
    - stats_arrays >=0.6.5
    - unicodecsv
    - voluptuous
    - whoosh
    - xlrd
    - xlsxwriter

test:
  imports:
    - brightway2

about:
  home: https://brightway.dev
  summary: 'Metapackage for brightway2 imports and documentation '
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: https://docs.brightway.dev
  dev_url: https://github.com/brightway-lca/brightway2

extra:
  recipe-maintainers:
    - cmutel
    - m-rossi
