{% set name = "brightway2" %}
{% set version = "2.4.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0b9fb69885337526dce830f41c137cfec9bb1464979d5472b6563ee9a42c0756

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - appdirs
    - asteval
    - bw2analyzer <0.10.99
    - bw2calc =1.8.2
    - bw2data =3.6.6
    - bw2io =0.8.12
    - bw2parameters >=0.6.5
    - docopt
    - eight
    - flask
    - future
    - lxml
    - numpy <2
    - peewee >=3.0
    - psutil
    - pyprind
    - requests
    - scipy
    - stats_arrays >=0.6.5
    - unicodecsv
    - voluptuous
    - whoosh
    - xlrd
    - xlsxwriter

test:
  requires:
    - python {{ python_min }}
  imports:
    - brightway2

about:
  home: https://brightway.dev
  summary: 'Metapackage for brightway2 imports and documentation '
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: https://docs.brightway.dev
  dev_url: https://github.com/brightway-lca/brightway2

extra:
  recipe-maintainers:
    - cmutel
    - m-rossi
